title: SoftMatterHacker.com
description: A homepage for the Complex Fluids group at UNSW  # >- this means to ignore newlines until "baseurl:" 


#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SoftMatterHackr
github_username:  SoftMatterHacker
  
# Build settings
remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme
- jekyll-relative-links
#  - jekyll-feed
#  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - talks.md
  - publications.md
